### ISSUE TITLE
Informative vs normative references

### ISSUE THREAD

**Issue by manger** [azet/draft-zauner-tls-aes-ocb#5]
RFC7253 "OCB Authenticated Encryption" should be a normative.
RFC6655 "AES-CCM Ciphersuites" can be informative.

**Comment by azet** [comment]
thanks for pointing that out, fixed in 923775a.

**Comment by manger** [comment]
I would make RFC7253 the normative reference for OCB, and leave the 2001 conference paper [OCB] as an informative reference.
RFC7253 is much easier to get (the reference in a hyperlink); has the precise terms such AEAD_AES_128_OCB_TAGLEN96 that is spec refers to; is written as a spec; and is recent (May 2014).
Section 7 "Acknowledgements" of RFC7253 talks about the evolution of OCB from the 2001 paper [OCB1] then 2004 work [OCB2] then 2011 work [OCB3] then tweaks for the RFC so I’m not sure that the original 2001 paper reflects the precise calculations implementers of draft-zauner-tls-aes-ocb need to perform.

**Comment by azet** [comment]
@manger thanks, changed to normative in 0ad6ed5. and OCB to informative in 8a67b288b09e9909aff6d72dbef4be56b41db4b0.
